version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    volumes:
      - ./sessions:/usr/src/app/sessions
    environment:
      - NODE_ENV=production
